package jp.go.nict.langrid.wrapper.templateparalleltext.importer;

import java.util.Arrays;

import com.google.api.client.googleapis.auth.oauth2.GoogleAuthorizationCodeFlow;
import com.google.api.client.http.javanet.NetHttpTransport;
import com.google.api.client.json.gson.GsonFactory;

/**
 * Get URL for OAuth2.0 confirmation page.
 * You have to
 * 1. create a project
 * 2. enable Drive API for the project
 * 3. create client id as native or installed app.
 * 4. replace CLIENT-ID, CLIENT-SECRET and REDIRECT-URI with information generated by 3.
 * @author Takao Nakaguchi
 */
public class GetConfirmationPageURL {
	public static void main(String[] args) throws Throwable{
		System.out.println(
				buildFlow()
				.newAuthorizationUrl()
				.setRedirectUri(redirectUri).build());
	}

	static GoogleAuthorizationCodeFlow buildFlow(){
		return new GoogleAuthorizationCodeFlow.Builder(
				new NetHttpTransport(), new GsonFactory(), clientId, clientSecret,
				Arrays.asList(
						"https://spreadsheets.google.com/feeds",
						"https://docs.google.com/feeds")
				)
				.build();
	}

	static String clientId = "CLIENT-ID";
	static String clientSecret = "CLIENT-SECRET";
	static String redirectUri = "REDIRECT-URI";
}
